#!/usr/bin/python3
#a_string = input("Tell me your name: ")
#a_number_1 = input("Tell me number 1: ")
#a_number_2 = input("Tell me number 2: ")
#a_boolean = False
#result = float(a_number_1) + float(a_number_2)

#print(f"{result}")
# am besten so: ist schnell und es ist egal, ob int, str, float
#print(f"A boolean: {a_string} for {result} and done")

import testmodule

items = ["null","eins","zwei"]
items.append("drei")
items.remove("eins")
print(items)
#print(f"{len(items)} Elements")

if "drei" in items:
    print("Found")
else:
   print("not found")

# complex datastructure

   
print()
testmodule.print_data(name="Test",item="Computer")
print()
testmodule.print_data(item="MyItem")   
