#!/usr/bin/python3
#a_string = input("Tell me your name: ")
#a_number_1 = input("Tell me number 1: ")
#a_number_2 = input("Tell me number 2: ")
#a_boolean = False
#result = float(a_number_1) + float(a_number_2)

#print(f"{result}")
# am besten so: ist schnell und es ist egal, ob int, str, float
#print(f"A boolean: {a_string} for {result} and done")

#import testmodule
import configparser
import python_sandbox_module

items = ["null","eins","zwei"]
items.append("drei")
items.remove("eins")
print(items)
#print(f"{len(items)} Elements")

if "drei" in items:
    print("Found")
else:
   print("not found")

# complex datastructure

   
print()
python_sandbox_module.print_data(name="Test",item="Computer")
print()
return_value=python_sandbox_module.print_data(item="MyItem")   
print(f"The function returned {return_value}")


users = {} # creates dictionary
users['sAMAccountName'] = {} # creates dictionary

# first user
username = 'richi23'
users['sAMAccountName'][username] = {} # creates key, must be there
users['sAMAccountName'][username]['lastname'] = 'Blackmore'
users['sAMAccountName'][username]['firstname'] = 'Ritchie'
users['sAMAccountName'][username]['aliases'] = ['Rich','Richard']
users['sAMAccountName'][username]['morning_greeting'] = 'Morning Ritchie!'
users['sAMAccountName'][username]['evening_greeting'] = 'Good evening Mr. Blackmore'

# second user
username = 'jon23'
users['sAMAccountName'][username] = {} # creates key, must be there
users['sAMAccountName'][username]['lastname'] = 'Lord'
users['sAMAccountName'][username]['firstname'] = 'Jon'
users['sAMAccountName'][username]['aliases'] = ['John','Johnny']
users['sAMAccountName'][username]['morning_greeting'] = 'Morning Jon!'
users['sAMAccountName'][username]['evening_greeting'] = 'Good evening Mr. Lord'

python_sandbox_module.greeting(users,'richi23')
python_sandbox_module.greeting(users,'jon23')

print ("Listing:")
dir()
